# Generated by Django 3.2.7 on 2022-01-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True)),
                ('data_created', models.DateField(auto_now_add=True)),
                ('data_update', models.DateField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/')),
                ('draft', models.BooleanField(default=True)),
            ],
        ),
    ]
